spring.application.name=todolist

spring.datasource.url=jdbc:h2:file:./data/todolist_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

spring.thymeleaf.cache=false

# ===============================
# SEGURANÇA (SPRING SECURITY)
# ===============================
spring.security.user.name=tiago
spring.security.user.password=qazedctgb98!
